/*TABELA DE REGISTRO ENTRE SEGUIDOR E SEGUINDO*/
SELECT
USR.USER_ID AS ID_USU
,USR.USER_NAME AS NOME_USU
,FLW.FOLLOWING_USER_ID_FK AS ID_SEGUINDO
,US.USER_NAME AS NOME_SEGUINDO
,FLW.USER_ID_FK AS QUEM_SEGUE_DE_VOLTA
,USR.USER_NAME AS NOME_QUEM_SEGUE_VOLTA
FROM USERS USR
INNER JOIN FOLLOWERS FLW ON (USR.USER_ID = FLW.USER_ID_FK)
INNER JOIN USERS US ON (FLW.FOLLOWING_USER_ID_FK = US.USER_ID);




/*TABELA DE SEGUINDO DE VOLTA*/
SELECT
FLW.FOLLOWING_USER_ID_FK AS ID_USER
,USR.USER_NAME AS NOME_USU
,FLW.USER_ID_FK AS QUEM_SEGUE
,SEGUIDOR.USER_NAME
FROM FOLLOWERS FLW
INNER JOIN USERS SEGUIDOR ON (FLW.USER_ID_FK = SEGUIDOR.USER_ID)
INNER JOIN USERS USR ON (FLW.FOLLOWING_USER_ID_FK = USR.USER_ID);








