SELECT
U1_NAME
,U2_NAME
FROM (
SELECT
CASE WHEN (POSTS1 < POSTS2) THEN U1_NAME END AS U1_NAME
,CASE WHEN (POSTS2 > POSTS1) THEN U2_NAME END AS U2_NAME
FROM (
SELECT
FLW.USER_ID_FK
,USR.USER_NAME AS U1_NAME
,USR.POSTS AS POSTS1
,FLW.FOLLOWING_USER_ID_FK
,US.USER_NAME AS U2_NAME
,US.POSTS AS POSTS2
FROM FOLLOWERS FLW
LEFT JOIN USERS USR ON (FLW.USER_ID_FK = USR.USER_ID)
LEFT JOIN USERS US ON (FLW.FOLLOWING_USER_ID_FK = US.USER_ID)
WHERE FLW.FOLLOWING_USER_ID_FK IN (
SELECT
FL.USER_ID_FK
FROM FOLLOWERS FL
WHERE FL.FOLLOWING_USER_ID_FK = FLW.USER_ID_FK
) 
ORDER BY FLW.USER_ID_FK )T )X
WHERE U1_NAME IS NOT NULL
